# This workflow will build a .NET project and create a release
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CD

on:
  push:
    tags:
      - "v*"

jobs:
  build:
  
    strategy:
        matrix:
          platform: [x86, x64, ARM64]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup WiX
      run: dotnet tool install --global wix
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:Platform=${{ matrix.platform }} -c Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VigilantMonitorSetup_${{ matrix.platform }}.msi
        path: Setup/bin/${{ matrix.platform }}/Release/en-US/VigilantMonitorSetup_${{ matrix.platform }}.msi

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download installers
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: "*.msi"
        fail_on_unmatched_files: true
        draft: true
